name: Run main.py

on: [push]

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

    - name: Run main.py
      run: python main.py
